import type { Locale } from '@/lib/i18n'

/**
 * نصوص صفحة الاستقبال v2 — عربي فصيح (كما في هوية اللبنة) وفرنسي.
 * كلّ رابط نسبي يُسبق باللغة في الصفحة نفسها.
 */
const AR = {
  nav: {
    home: 'الرئيسية',
    about: 'من نحن',
    services: 'خدماتنا',
    projects: 'مشاريعنا',
    track: 'تتبّع مطلبي',
    cta: 'سجّل مطلبك',
    lang: 'FR',
    langName: 'Français',
    menuTitle: 'القائمة',
    menuOpen: 'افتح القائمة',
    menuClose: 'أغلق القائمة',
    back: 'رجوع',
    ctaShort: 'سجّل مطلبك',
    group: 'الصفحات',
  },
  hero: {
    title: 'إلى مستقبل أجمل',
    sub: 'اللبنة للبناء والإعمار',
    text: 'نبنيو الدار على قدّ إمكانياتك، بكلفة واضحة من الأوّل وخطوات تعرفها. سجّل مطلب سكنك مرّة واحدة، ونرافقك من الدراسة إلى مفتاح الدار.',
    cta1: 'ابدأ مشروعك الآن',
    cta2: 'تعرّف على خدماتنا',
    free: 'التسجيل بدون معاليم — ما ناخذو حتّى مليم من الحريف',
    videoTitle: 'تعرّف على خدماتنا',
    videoNote: 'فيديو تعريفي مؤقّت — النسخة النهائية قريباً',
    close: 'إغلاق',
    alt: 'مهندس يشرح المخطّط لعائلة أمام دار في طور البناء في صفاقس',
  },
  stats: [
    { n: '0', l: 'معاليم على المواطن' },
    { n: '16', l: 'معتمدية في صفاقس' },
    { n: '5', l: 'مستويات تشطيب' },
    { n: '', l: 'تنمية مستدامة' },
  ],
  services: {
    eyebrow: 'خدماتنا',
    title: 'حلول متكاملة لبناء حياة أفضل',
    text: 'من الفكرة إلى التسليم، نرافقك في كل مرحلة لنحقق معًا مسكنًا يليق بك وبعائلتك.',
    cta: 'ابدأ مطلبك — بدون معاليم',
    items: [
      { t: 'بناء المساكن', d: 'بناء فوق أرضك بمواصفات تختارها بنفسك', href: '/demande?type=build_on_land' },
      { t: 'التطوير العقاري', d: 'أرض ودار، أو شقة في مشروع قانوني', href: '/demande?type=land_and_house' },
      { t: 'بناء مستدام', d: 'طرق بناء مدروسة بمواد محلية وجودة مراقبة', href: '/systemes' },
      { t: 'مرافقة شاملة', d: 'من الدراسة إلى التسليم، خطوة بخطوة', href: '/suivi' },
    ],
  },
  about: {
    eyebrow: 'من نحن',
    title: 'اللبنة للبناء والإعمار',
    text: 'شركة تونسية خاصة مستقلة للمقاولات. ننطلق من حاجتك للسكن أو البناء، ندرس وضعيتك وإمكانياتك، ونجمع حول مشروعك الخبرات والحلول المناسبة، من الدراسة إلى التنفيذ والتسليم. كل شيء واضح من البداية: الكلفة، الخطوات، ودورنا.',
    tagline: 'نفهم حاجتك، نلقى الحل، ونبنيه معاك.',
    feats: ['شركة خاصة مستقلة', 'شفافية في الكلفة والخطوات', 'لسنا جهة تمويل'],
    cta: 'اقرأ من نحن',
    script: 'Tunis\nalways a better\ntomorrow',
    photoCta: 'شاهد الحالات المنجزة',
    mapTitle: 'كل مشروع لبنة لبناء المستقبل',
    mapSub: 'صفاقس · المرحلة التجريبية',
    mapFrameTitle: 'خريطة تونس — صفاقس',
    mapOpen: 'افتحها في خرائط Google',
    alt: 'بنّاؤون يرفعون جدار دار بالطوب تحت شمس تونس',
  },
  how: {
    eyebrow: 'كيف نعمل',
    title: 'أربع خطوات… من الطلب إلى المفتاح',
    steps: [
      { t: 'سجّل طلبك', d: 'خمس خطوات من الهاتف، في أقل من ثلاث دقائق وبلا حساب.' },
      { t: 'ندرس قدرتك', d: 'ميزانية تقديرية وقسط شهري ممكن، ورمز خاص لمتابعة ملفك.' },
      { t: 'نجد لك العرض', d: 'مشروع أو أرض أو شركة بناء تناسب منطقتك وميزانيتك.' },
      { t: 'نرافقك حتى المفتاح', d: 'من الموعد الأول إلى تسليم الدار.' },
    ],
  },
  methods: {
    eyebrow: 'طرق البناء',
    title: 'كيفاش نبنيو الدار؟',
    text: 'نختارو معاك الطريقة اللي تناسب أرضك وميزانيتك: هيكل خرساني وجدران بالطوب أو بالبلوك، وأسقف جاهزة تربح الوقت وتضبط الكلفة.',
    all: 'اعرف أكثر عن طرق البناء',
    items: [
      {
        t: 'هيكل خرساني وجدران بالطوب',
        d: 'الطريقة الكلاسيكية: أعمدة وروافد من الخرسانة المسلّحة، وجدران من الآجر الأحمر.',
        alt: 'بنّاؤون يرفعون جدار دار بالطوب الأحمر',
      },
      {
        t: 'البناء بالبلوك الإسمنتي',
        d: 'بلوك إسمنتي للجدران: إنجاز أسرع، وعزل جيّد حين يُنفَّذ بإتقان.',
        alt: 'بنّاء يضع بلوك إسمنتي في جدار دار في طور البناء',
      },
      {
        t: 'الأسقف الجاهزة',
        d: 'روافد مسبقة الصنع وهورديس: سقف يُركَّب في أيام، أخفّ وزناً وبكلفة مضبوطة.',
        alt: 'تركيب سقف جاهز من روافد مسبقة الصنع وهورديس',
      },
    ],
  },
  projects: {
    eyebrow: 'مشاريعنا',
    title: 'قصص حقيقية … لمستقبل أجمل',
    text: 'نحوّل الأفكار إلى واقع. اكتشف الحالات المنجزة، المنشورة بموافقة أصحابها.',
    all: 'عرض جميع الحالات',
    items: [
      { t: 'بناء فوق أرضك', l: 'صفاقس', href: '/demande?type=build_on_land' },
      { t: 'شقق في مشاريع قانونية', l: 'صفاقس الكبرى', href: '/demande?type=apartment' },
      { t: 'أرض ودار', l: 'بعقد واحد واضح', href: '/demande?type=land_and_house' },
    ],
  },
  sticky: { cta: 'سجّل مطلبك — بدون معاليم' },
  footer: {
    tagline: 'Same roots · Brighter tomorrows',
    legal: 'اللبنة للبناء والإعمار · AL-LUBNA — نسخة تجريبية',
    privacy: 'حماية المعطيات',
    ctaTitle: 'جاهز تبدأ مشروعك؟',
    ctaText: 'سجّل مطلبك في دقائق، بدون معاليم، ونرجعولك بالحلّ اللي يناسبك.',
  },
}

export type LandingCopy = typeof AR

const FR: LandingCopy = {
  nav: {
    home: 'Accueil',
    about: 'Qui sommes-nous',
    services: 'Services',
    projects: 'Projets',
    track: 'Suivre ma demande',
    cta: 'Déposer ma demande',
    lang: 'AR',
    langName: 'العربية',
    menuTitle: 'Menu',
    menuOpen: 'Ouvrir le menu',
    menuClose: 'Fermer le menu',
    back: 'Retour',
    ctaShort: 'Commencer',
    group: 'Pages',
  },
  hero: {
    title: 'vers un avenir meilleur',
    sub: 'AL-LUBNA — Construction & Développement',
    text: 'Nous construisons votre maison à la mesure de vos moyens, avec un coût clair dès le départ et des étapes connues. Déposez votre demande de logement une seule fois : nous vous accompagnons de l’étude jusqu’aux clés.',
    cta1: 'Commencer mon projet',
    cta2: 'Découvrir nos services',
    free: "Dépôt sans frais — nous ne prenons rien au citoyen",
    videoTitle: 'Découvrir nos services',
    videoNote: 'Vidéo de présentation provisoire — la version finale arrive bientôt',
    close: 'Fermer',
    alt: 'Un ingénieur explique les plans à une famille devant une maison en construction à Sfax',
  },
  stats: [
    { n: '0', l: 'frais pour le citoyen' },
    { n: '16', l: 'délégations à Sfax' },
    { n: '5', l: 'niveaux de finition' },
    { n: '', l: 'Développement durable' },
  ],
  services: {
    eyebrow: 'Nos services',
    title: 'Des solutions complètes pour une vie meilleure',
    text: 'De l’idée à la livraison, nous vous accompagnons à chaque étape pour un logement à votre mesure.',
    cta: 'Déposer ma demande — sans frais',
    items: [
      { t: 'Construction', d: 'Construire sur votre terrain, selon vos choix', href: '/demande?type=build_on_land' },
      { t: 'Développement immobilier', d: 'Terrain + maison, ou appartement dans un projet légal', href: '/demande?type=land_and_house' },
      { t: 'Construction durable', d: 'Méthodes étudiées, matériaux locaux, qualité contrôlée', href: '/systemes' },
      { t: 'Accompagnement complet', d: 'De l’étude à la livraison, étape par étape', href: '/suivi' },
    ],
  },
  about: {
    eyebrow: 'Qui sommes-nous',
    title: 'AL-LUBNA',
    text: "Entreprise tunisienne privée et indépendante de construction. Nous partons de votre besoin de logement ou de construction, étudions votre situation et vos moyens, puis réunissons autour de votre projet les compétences et solutions adaptées, de l'étude à l'exécution et à la livraison. Tout est clair dès le départ : coûts, étapes et notre rôle.",
    tagline: 'Nous comprenons votre besoin, trouvons la solution et la bâtissons avec vous.',
    feats: ['Entreprise privée indépendante', 'Transparence sur coûts et étapes', 'Pas un organisme de financement'],
    cta: 'Qui sommes-nous',
    script: 'Tunis\nalways a better\ntomorrow',
    photoCta: 'Voir les réalisations',
    mapTitle: "Chaque projet est une brique pour bâtir l'avenir",
    mapSub: 'Sfax · phase pilote',
    mapFrameTitle: 'Carte de la Tunisie — Sfax',
    mapOpen: 'Ouvrir dans Google Maps',
    alt: 'Des maçons montent un mur en briques sous le soleil tunisien',
  },
  how: {
    eyebrow: 'Comment ça marche',
    title: 'Quatre étapes… de la demande aux clés',
    steps: [
      { t: 'Déposez votre demande', d: 'Cinq étapes depuis le téléphone, moins de trois minutes, sans compte.' },
      { t: 'Nous étudions votre capacité', d: 'Budget estimatif, mensualité possible et un code privé pour suivre votre dossier.' },
      { t: 'Nous trouvons l’offre', d: 'Un projet, un terrain ou un constructeur adapté à votre zone et à votre budget.' },
      { t: 'Nous vous accompagnons', d: 'Du premier rendez-vous jusqu’à la remise des clés.' },
    ],
  },
  methods: {
    eyebrow: 'Méthodes de construction',
    title: 'Comment construisons-nous ?',
    text: 'Nous choisissons avec vous la méthode adaptée à votre terrain et à votre budget : ossature en béton avec murs en briques ou en parpaings, et planchers préfabriqués qui font gagner du temps et maîtrisent le coût.',
    all: 'En savoir plus sur les méthodes',
    items: [
      {
        t: 'Ossature béton et murs en briques',
        d: 'La méthode classique : poteaux et poutres en béton armé, murs en briques rouges.',
        alt: 'Des maçons montent un mur en briques rouges',
      },
      {
        t: 'Construction en parpaings',
        d: 'Blocs de béton pour les murs : exécution plus rapide, bonne isolation quand la mise en œuvre est soignée.',
        alt: 'Un maçon pose un parpaing sur un mur en construction',
      },
      {
        t: 'Planchers préfabriqués',
        d: 'Poutrelles préfabriquées et hourdis : un plancher posé en quelques jours, plus léger, au coût maîtrisé.',
        alt: 'Pose d’un plancher préfabriqué en poutrelles et hourdis',
      },
    ],
  },
  projects: {
    eyebrow: 'Nos projets',
    title: 'Des histoires vraies… pour un avenir meilleur',
    text: 'Nous transformons les idées en réalité. Découvrez les cas résolus, publiés avec l’accord de leurs propriétaires.',
    all: 'Voir toutes les réalisations',
    items: [
      { t: 'Construire sur votre terrain', l: 'Sfax', href: '/demande?type=build_on_land' },
      { t: 'Appartements dans des projets légaux', l: 'Grand Sfax', href: '/demande?type=apartment' },
      { t: 'Terrain + maison', l: 'Un seul contrat clair', href: '/demande?type=land_and_house' },
    ],
  },
  sticky: { cta: 'Déposer ma demande — sans frais' },
  footer: {
    tagline: 'Same roots · Brighter tomorrows',
    legal: 'AL-LUBNA — Construction & Développement — version pilote',
    privacy: 'Protection des données',
    ctaTitle: 'Prêt à commencer votre projet ?',
    ctaText: 'Déposez votre demande en quelques minutes, sans frais : nous revenons vers vous avec la solution adaptée.',
  },
}

export const landingCopy: Record<Locale, LandingCopy> = { ar: AR, fr: FR }
